spring.application.name=agentic
spring.docker.compose.enabled=false

# Connection
spring.ai.google.genai.api-key=AIzaSyC_8Ev7tmgkDBO29isT_vfz7ccVE4CYOWY

# Model Selection (Standardized in 2.0)
spring.ai.google.genai.chat.options.model=gemini-1.5-flash
spring.ai.google.genai.chat.options.temperature=0.7

# Optional: Explicitly enable this specific chat model
spring.ai.model.chat=google-genai